version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: deps(go)
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: deps(docker)
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: deps(actions)
  groups:
    actions:
      patterns:
        - "actions/*"
